AgeGroup = {
    "13-19 yrs" : "13-19 yrs",
    ">60 yrs" : ">60 yrs",
    "20-29 yrs" : "20-29 yrs",
    "50-59 yrs" : "50-59 yrs",
    "40-49 yrs" : "40-49 yrs",
    "30-39 yrs" : "30-39 yrs",
    "na" : "Unknown",
    "<5 yrs" : "<5 yrs",
    "6-12 yrs" : "6-12 yrs",
    "pt is in their 60's" : ">60 yrs",
    "pt is 13-19 years" : "13-19 yrs",
    "pt is in their 20's" : "20-29 yrs",
    "pt is in their 40's" : "40-49 yrs",
    "pt is in their 50's" : "50-59 yrs",
    "pt is in their 30's" : "30-39 yrs",
    "unknown adult 20 years or more" : "Unknown",
    "pt is 5 years or less" : "<5 yrs",
    "pt is in their 70's" : ">60 yrs",
    "pt is 90 years or more" : ">60 yrs",
    "pt is in their 80's" : ">60 yrs",
    "pt is 6-12 years" : "6-12 yrs",
    "unknown age" : "Unknown",
    "10--15" : "Unknown",
    "0--2" : "<5 yrs",
    "20--29" : "20-29 yrs",
    "unknown" : "Unknown",
    "6--9" : "6-12 yrs",
    "16--19" : "13-19 yrs",
    "30--39" : "30-39 yrs",
    "40--49" : "Unknown",
    "50--65" : "Unknown",
    "65+" : ">60 yrs",
    "3--5" : "<5 yrs",
    "30s" : "30-39 yrs",
    "50s" : "50-59 yrs",
    "20s" : "20-29 yrs",
    "70s" : ">60 yrs",
    "60s" : ">60 yrs",
    "13-19 years" : "13-19 yrs",
    "unknown adult (>=20 yrs)" : "Unknown",
    "40s" : "40-49 yrs",
    "80s" : ">60 yrs",
    "0-5 yrs" : "<5 yrs",
    ">=90" : ">60 yrs",
    "60-69 yrs" : ">60 yrs",
    "70-79 yrs" : ">60 yrs",
    "6-12 years" : "6-12 yrs"
	}
	
SEX = {
	'f' : 'Female',
	'm' : 'Male',
	'u' : 'Unknown',
	'p' : 'Female',
	'male' : 'Male',
	'female' : 'Female',
	'pregnant' : 'Female',
	'unknown' : 'Unknown'
	}
	
Reason = {
    'intentional/abuse' : 'Intentional - Abuse',
    'adverse reaction/other' : 'Adverse Reaction - Drug',
    'adverse' : 'Adverse Reaction - Drug',
    'adverse reaction/drug' : 'Adverse Reaction - Drug',
    'intentional/suspected suicide' : 'Intentional - Suspected Suicide',
    'unintentional/therapeutic error' : 'Unintentional - Other',
    'intentional/misuse' : 'Intentional - Misuse',
    'unintentional/general' : 'Unintentional - General',
    'intentional/unknown' : 'Intentional - Other',
    'unknown reason' : 'Unknown',
    'unintentional - accidental' : 'Unintentional - Other',
    'unintentional/misuse' : 'Unintentional - Misuse',
    'n/a' : 'Unknown',
    'unintentional/unknown' : 'Unintentional - Other',
    'unintentional/occupational' : 'Unintentional - Other',
    'unintentional/food poisoning' : 'Unintentional - Other',
    'unintentional/environmental' : 'Unintentional - Other',
    'malicious' : 'Intentional - Other',
    'contamination/tampering' : 'Intentional - Other',
    'misuse' : 'Unintentional - Misuse',
    'intentional - misuse' : 'Intentional - Misuse',
    'intentional - abuse' : 'Intentional - Abuse',
    'intentional - suspected suicide' : 'Intentional - Suspected suicide',
    'accidental' : 'Unintentional - Other',
    'abuse' : 'Intentional - Abuse',
    'unknown' : 'Unknown',
    'administration error' : 'Intentional - Other',
    'unk,circumstance' : 'Unknown',
    'suicide' : 'Intentional - Suspected Suicide',
    'inflicted' : 'Unknown',
    'other, intent. circum.' : 'Intentional - Other',
    'unk, intentional circ.' : 'Intentional - Other',
    'unintentional - environmental' : 'Unintentional - Other',
    'other, uninten. circumstance' : 'Unintentional - Other',
    'other,circumstance' : 'Unknown',
    'intentional' : 'Intentional - Other',
    'unintentional' : 'Unintentional - Other',
    'unintentional - environmental' : 'Unintentional - Other',
    'contamination - tampering' : 'Intentional - Other'
	}

ExposureSite = {
    'other residence' : 'Other residence',
    'own residence' : 'Own residence',
    'unknown' : 'Unknown',
    'workplace' : 'Workplace',
    'health care facility *(code)' : 'Health care facility',
    'school' : 'School',
    'other *(code)' : 'Other',
    'publlic area' : 'Public area',
    'n/a' : 'Unknown',
    "public area" : "Public area",
    'health care facility' : 'Health care facility',
    'public area' : 'Public area',
    'restaurant / food service' : 'Restaurant/food service',
    'other' : 'Other'
    }	
	
SubstanceFormula = {
	'solid (tablets/capsules/caplets)' : 'Solid (tablets/capsules/caplets)',
	'liquid' : 'Liquid',
	'unknown' : 'Unknown',
	'other' : 'Other',
	'patch / dermal' : 'Patch/dermal',
	'powder/granules' : 'Powder/granules',
	'aerosol/mist/spray/gas' : 'Aerosol/mist/spray/gas',
	'cream/lotion/gel' : 'Cream/lotion/gel',
	'null' : 'Unknown',
	'tablet/capsule' : 'Solid (tablets/capsules/caplets)',
	'solid (tablets / capsules / caplets)' : 'Solid (tablets/capsules/caplets)',
	'powder / granules' : 'Powder/granules',
	'patch' : 'Patch/dermal',
    'solid (tablets / capsules / caplets)' : 'Solid (tablets/capsules/caplets)',
    'unknown' : 'Unknown',
    'liquid' : 'Liquid',
    'other' : 'Other'
	}

	
Route = {
    'ingest' : 'Ingestion',
    'dose_inadvertenttwice' : 'Unknown',
    'dose_otherincdose' : 'Unknown',
    'parent' : 'Parenteral',
    'dose_incformgiven' : 'Unknown',
    'dermal' : 'Dermal',
    'rt_unk' : 'Unknown',
    'null' : 'Unknown',
    'dose_incroute' : 'Unknown',
    'rt_other' : 'Other',
    'inhale' : 'Inhalation/nasal',
    'dose_otherunkthererr' : 'Other',
    'dose_cuperr' : 'Unknown',
    'dose_incformdisp' : 'Unknown',
    'dose_10folderr' : 'Unknown',
    'ocular' : 'Ocular',
    'route_vaginal' : 'Other',
    'rectal' : 'Other',
    'conf_containerxfr' : 'Unknown',
    'route_rectal' : 'Rectal',
    'dose_druginteraction' : 'Unknown',
    'misc_unknown' : 'Unknown',
    '1.oral' : 'Ingestion',
    '1.oral  2.route, other' : 'multiple',
    'null' : 'Unknown',
    '1.inhalation' : 'Inhalation/nasal',
    '1.unk ,route' : 'Unknown',
    '1.dermal' : 'Dermal',
    '1.ocular' : 'Ocular',
    '1.inhalation  2.oral  3.parenteral' : 'multiple',
    '1.inhalation  2.oral' : 'multiple',
    '1.parenteral' : 'Parenteral',
    '1.dermal  2.oral' : 'multiple',
    '1.route, other' : 'Other',
    '1.route, other  2.unk ,route' : 'multiple'
	}

	
PatientFlow = {
    'in/enroute to hcf' : 'Patient already in (en route to) HCF',
    'managed on site (non-hcf)' : 'Managed on site',
    'unknown' : 'Unknown',
    'referred to hcf' : 'Patient was referred to a HCF',
    'other *(code)' : 'Other',
    'n/a' : 'Unknown',
    'er,remain at' : 'Patient already in (en route to) HCF',
    'home,remain at' : 'Managed on site',
    'regional center,go to' : 'Patient was referred to a HCF',
    'er,go to' : 'Patient was referred to a HCF',
    'icu,remain at' : 'Patient already in (en route to) HCF',
    'office/clinic,remain at' : 'Managed on site',
    'other,remain at' : 'Managed on site',
    'office/clinic,go to' : 'Patient was referred to a HCF',
    'go to other' : 'Other',
    'not completed' : 'Unknown',
    'managed on site - not hcf (e.g. treated at home)' : 'Managed on site',
    'patient was referred by pcc to a hcf' : 'Patient was referred to a HCF',
    'managed on site (non health care facility)' : 'Managed on site',
    'minor effectmanaged on site (non health care facility)' : 'Managed on site',
    'patient already in (enroute to) hcf when pcc called' : 'Patient already in (en route to) HCF',
    '1.oral  2.route, other' : 'multiple',
    'null' : 'Unknown',
    '1.inhalation' : 'Inhalation/nasal',
    '1.unk ,route' : 'Unknown',
    '1.dermal' : 'Dermal',
    '1.ocular' : 'Ocular',
    '1.inhalation  2.oral  3.parenteral' : 'multiple',
    '1.inhalation  2.oral' : 'multiple',
    '1.parenteral' : 'Parenteral',
    '1.dermal  2.oral' : 'multiple',
    '1.route, other' : 'Other',
    '1.route, other  2.unk ,route' : 'multiple'
	}

	
HospitalFlow = {
	'admitted to critical care unit' : 'Admitted to critical care unit',
	'treated/evaluated and released' : 'Treated/evaluated and released',
	'patient lost to follow-up/left ama' : 'Patient lost to follow-up/left AMA',
	'admitted to noncritical care unit' : 'Admitted to noncritical care unit',
	'admitted to psychiatric facility' : 'Admitted to psychiatric facility',
	'n/a' : 'Unknown',
	'er' : 'Admitted to critical care unit',
	'home' : 'Treated/evaluated and released',
	'null' : 'Unknown',
	'unk,disposition' : 'Unknown',
	'icu' : 'Admitted to critical care unit',
	'office/clinic' : 'Admitted to noncritical care unit',
	'not completed' : 'Unknown',
	'ward' : 'Admitted to noncritical care unit'
	}

	
OutCome = {
    'major effect' : 'Major effect',
    'major effect' : 'Major effect',
    'moderate effect' : 'Moderate effect',
    'minor effect' : 'Minor effect',
    'minor effect' : 'Minor effect',
    'minimal clinical effects possible' : 'Minimal clinical effects possible',
    'not followed, minimal clinical effects possible' : 'Minimal clinical effects possible',
    'no effect' : 'No effect',
    'no effect' : 'No effect',
    'judged as nontoxic - expect no effect' : 'Not followed, judged as nontoxic exposure',
    'unable to follow - potentially toxic exposure' : 'Unable to follow - potentially toxic exposure',
    'unrelated - probably not responsible' : 'Unrelated - probably not responsible',
    'confirmed non exposure' : 'Confirmed non exposure',
    'death' : 'Death',
    'death' : 'Death',
    'n/a' : 'Unknown',
    'x-death, indirect report' : 'Death, Indirect Report',
    'unk,non-toxic' : 'Not followed, judged as nontoxic exposure',
    'null' : 'Unknown',
    'unk,medical outcome' : 'Unknown',
    'unk,potentially toxic' : 'Unable to follow - potentially toxic exposure',
    'not completed' : 'Unknown',
    'unable to follow, judged as a potentially toxic exposure' : 'Unable to follow - potentially toxic exposure',
    'not followed, judged as nontoxic exposure' : 'Not followed, judged as nontoxic exposure',
    'unrelated effect' : 'Unrelated - probably not responsible'
	}

	
Acuity = {
	'acute-on-chronic' : 'Acute-on-Chronic',
    'acute on chronic' : 'Acute-on-Chronic',
	'unknown' : 'Unknown',
	'acute' : 'Acute',
	'chronic' : 'Chronic',
	'n/a' : 'Unknown'
	}
    
CallerRelation = {
    "nurse" : "Professional",
    "811 hlth link" : "Professional",
    "physician" : "Professional",
    "pharmacist" : "Professional",
    "paramedic" : "Professional",
    "911" : "Professional",
    "ward clerk" : "Professional",
    "amb dispatch" : "Professional",
    "veterinarian" : "Professional",
    "police" : "Professional",
    "vet clinic" : "Unknown",
    "vet tech" : "Unknown",
    "sister" : "Public",
    "self" : "Public",
    "wife" : "Public",
    "daughter" : "Public",
    "animal owner" : "Public",
    "other" : "Public",
    "care giver" : "Public",
    "mother" : "Public",
    "co-worker" : "Public",
    "friend" : "Public",
    "boyfriend" : "Public",
    "other family" : "Public",
    "husband" : "Public",
    "father" : "Public",
    "girlfriend" : "Public",
    "grandmother" : "Public",
    "caregiver" : "Public",
    "aunt" : "Public",
    "np" : "Public",
    "teacher" : "Public",
    "grandfather" : "Public",
    "son" : "Public"
    }