#too much inconsistency in source data to account for caps, so all inputs will just be forced to lower case before being filtered through this dict
#this is separate cleaning_dicts.py because the process of cleaning this variable is different
#some values are formatted as "1.symptom_a 2.symptom_b etc.". These are split into one row per item and then cleaned. 

symptoms_dict = {
    'abdominal pain':'Abdominal pain',
    'acidosis':'Acidosis',
    'anion gap':'Acidosis',
    'osmolal gap':'Acidosis',
    'adr to treatment':'ADR to treatment',
    'alkalosis':'Alkalosis',
    'anorexia':'Anorexia',
    'anxiety':'Anxiety',
    'anxiety  -other':'Anxiety',
    'ast, alt >100<=1000':'AST, ALT >100<=1000',
    'ast, alt >1000':'AST, ALT >1000',
    'bilirubin':'Bilirubin',
    'bleeding(other)':'Bleeding',
    'blood per rectum':'Bleeding',
    'bullae':'Bullae',
    'c.n.s.-other':'C.N.S.-Other',
    'c.n.s.-other  -other':'C.N.S.-Other',
    'c.n.s.':'C.N.S.-Other',
    'arrest':'Cardiac Arrest',
    'asystole':'Cardiac Arrest',
    'cardiac arrest':'Cardiac Arrest',
    'bradycardia':'Cardiovascular - other',
    'c.v.s.-other':'Cardiovascular - other',
    'dysrhythmia/other':'Cardiovascular - other',
    'dysrhythmia/v.tach-fib':'Cardiovascular - other',
    'hypertension':'Cardiovascular - other',
    'hypotension':'Cardiovascular - other',
    'rhythm disturbance':'Cardiovascular - other',
    'tachycardia':'Cardiovascular - other',
    'cardiovascular - other':'Cardiovascular - other',
    'cva':'Cardiovascular - other',
    'cellulitis':'Cellulitis',
    'chest pain':'Chest Pain',
    'chest pain  -other':'Chest Pain',
    'chest x-ray (+) findings':'Chest X-Ray Findings',
    'chest xray (+)findings':'Chest X-Ray Findings',
    'chest x-ray (+)findings':'Chest X-Ray Findings',
    'coma':'Coma',
    'conduct disturb':'Conduct disturb',
    'confusion':'Confusion',
    'constipation':'Constipation',
    'cytopenia':'Cytopenia',
    'deafness':'Deafness',
    'dehydration':'Dehydration',
    'diarrhea':'Diarrhea',
    'difficulty breathing':'Difficulty breathing',
    'apnea':'Difficulty breathing',
    'cough & choke':'Difficulty breathing',
    'resp arrest':'Difficulty breathing',
    'resp depression':'Difficulty breathing',
    'respiratory depression':'Difficulty breathing',
    'respiratory-other':'Difficulty breathing',
    'tachypnea':'Difficulty breathing',
    'dyspnea':'Difficulty breathing',
    'respiratory':'Difficulty breathing',
    'dizzy/vertigo':'Dizzy/Vertigo',
    'vertigo/dizziness':'Dizzy/Vertigo',
    'vertigo':'Dizzy/Vertigo',
    'drowsiness':'Drowsiness',
    'drowsy/lethargy':'Drowsiness',
    'dysphagia':'Dysphagia',
    'ecg changes-other':'ECG Changes-Other',
    'edema':'Edema',
    'oropharyhgeal edema':'Edema',
    'papilledema':'Edema',
    'pulmonary edema':'Edema',
    'elyte abnormality':'Elyte Abnormality',
    'diaphoresis':'Excess Secretions',
    'excess secretions':'Excess Secretions',
    'lacrimation':'Excess Secretions',
    'urinary incontinence':'Excess Secretions',
    'fever':'Fever',
    'g.i.-other':'G.I.-Other',
    'hematemesis':'G.I.-Other',
    'melena':'G.I.-Other',
    'ileus':'G.I.-Other',
    'g.i.':'G.I.-Other',
    'hallucinate':'Hallucinations',
    'hallucinations':'Hallucinations',
    'headache':'Headache',
    'cpk elevation':'Hemo/myoglobinuria',
    'hematuria':'Hemo/myoglobinuria',
    'hemo/myoglobinuria':'Hemo/myoglobinuria',
    'rhabdo':'Hemo/myoglobinuria',
    'hemolysis':'Hemo/myoglobinuria',
    'hives/welts':'Hives/Welts',
    'hyperglycemia':'Hyperglycemia',
    'hypoglycemia':'Hypoglycemia',
    'hypothermia':'Hypothermia',
    'pneumonitis':'Inflammation',
    'red eye-conjunctivitis':'Inflammation',
    'intoxicated':'Intoxicated',
    'agit/irrit':'Irritation',
    'agitation':'Irritation',
    'irrit&pain (ocular)':'Irritation',
    'irritation, dermal':'Irritation',
    'irritation, ocular':'Irritation',
    'irritation/pain':'Irritation',
    'oral irritation':'Irritation',
    'pruritis':'Irritation',
    'rash':'Irritation',
    'throat irritation':'Irritation',
    'oxalate crystals urine':'Kidney injury',
    'renal failure':'Kidney injury',
    'scr increase':'Kidney injury',
    'muscle rigidity':'Muscle Rigidity',
    'bronchospasm':'Muscle spasms',
    'dystonia':'Muscle spasms',
    'fasciculation':'Muscle spasms',
    'tremor':'Muscle spasms',
    'tremors':'Muscle spasms',
    'nausea':'Nausea/vomiting',
    'vomiting':'Nausea/vomiting',
    'nausea/dizziness':'Nausea/vomiting',
    'null':'Unknown',
    'numbness':'Numbness',
    'obtunded':'Obtunded',
    'oliguria/anuria':'Oliguria/anuria',
    'urinary retention':'Oliguria/anuria',
    'oral burns':'Oral Burns',
    'local-other':'Other',
    'mult chem sens':'Other',
    'other':'Other',
    'symptom, other':'Other',
    'local':'Other',
    'dic':'Other Coagulopathy',
    'other coagulopathy':'Other Coagulopathy',
    'pt prolongation':'Other Coagulopathy',
    'other lft':'Other LFT',
    'pain':'Pain',
    'pain(other)':'Pain',
    'ataxia':'Paralysis',
    'ataxia  -other  -other':'Paralysis',
    'paralysis':'Paralysis',
    'periph neuropathy':'Paralysis',
    'puncture/sting':'Puncture/sting',
    'seizure':'Seizure',
    'seizure (mult/discrete)':'Seizure',
    'seizure (single)':'Seizure',
    'seizure (status)':'Seizure',
    'cyanosis':'Skin discoloration',
    'ecchymosis':'Skin discoloration',
    'erythema':'Skin discoloration',
    'pallor':'Skin discoloration',
    'slurred speech':'Slurred Speech',
    'syncope':'Syncope',
    'tinnitus':'Tinnitus',
    'urine color change':'Urine Color Change',
    'blurred vision':'Visual Defect',
    'miosis':'Visual Defect',
    'mydriasis':'Visual Defect',
    'nystagmus':'Visual Defect',
    'photophobia':'Visual Defect',
    'pupils nr':'Visual Defect',
    'visual defect':'Visual Defect',
    'muscle weakness':'Weakness',
    'weakness':'Weakness'
}